### ISSUE TITLE
Missing CSV files

### ISSUE THREAD

**Issue by danolson1** [RyanTaggard/county-status#1]
Hey Ryan,

In you DFR Travel Map Code.py file, there are several links to CSV files which are not available in the repository. Can you please add them?

/Users/ryantaggard/Desktop/COVID-19/Current County Status Map/Interactive/NYC_Boro.csv
/Users/ryantaggard/Desktop/COVID-19/Current County Status Map/co-est2019-alldata.csv

Thanks,
Dan

**Comment by chriscallahanuvm** [comment]
The files are available at the URLs provided in the comments in the script. 

https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e/data
https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/

**Comment by danolson1** [comment]
Found them. Thanks.
