### ISSUE TITLE
Data Discrepancy from Vt Heat Map

### ISSUE THREAD

**Issue by walkerworks** [RyanTaggard/county-status#3]
I've ported this to C# .NET Core - but there seems to be a data issue that we're both running into. I'm wondering if you have any insight into it?
The heat map at https://dfr.vermont.gov/about-us/covid-19/modeling/covid-19-modeling-graphics - which supposedly uses the same Johns Hopkins data and the same algorithm as your script, comes up with slightly different results.

Have you noticed this?

**Comment by RyanTaggard** [comment]
The parameters used to create the map changed very slightly about two weeks ago, but hadn't yet filtered down to our GitHub page. The new version should align with both the heat map on the DFR site and the travel map previously used to determine quarantine requirements.
